title: "Paper Title Here"

author: "Author(s) Name(s)"
institution: "Affiliated Institution(s)"

navbar-links:
  Home: ""
  Abstract: "#abstract"
  Results: "#results"
  Citation: "#citation"
  Try the Product: "https://product-trial-link-here"
  arXiv: "https://arxiv-link-here"

# Image to show in the navigation bar - you can replace this with your paper's image or logo
avatar: "/assets/img/paper-image.png"
round-avatar: true

# Footer social media links (optional)
social-network-links:
  email: "contact-email@example.com"
  github: "github-username"
  twitter: "twitter-handle"
  linkedin: "linkedin-profile"

# Custom sections for your paper
custom-sections:
  - title: "Abstract"
    id: "abstract"
    content: "Your paper's abstract here. You can write a brief summary of your paper's objectives, methodology, and key findings."
  
  - title: "Results"
    id: "results"
    content: "Highlight of the paper's results. Include any figures, tables, or key data points that showcase the outcomes of your research."
  
  - title: "Citation"
    id: "citation"
    content: "How to cite this paper: Author(s). (Year). Title. Journal/Conference. DOI/Link"

# You might need to add or edit actual Markdown (.md) files in your repository for content like abstract, results, etc.
# This config setup assumes static content will be added directly in HTML or Markdown files referencing these IDs.

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # Enable comments for interaction
      social-share: true # Enable social media sharing buttons

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
